# Generated by Django 4.1.3 on 2022-11-25 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcode',
            name='soni',
            field=models.CharField(blank=True, choices=[('100', '100 talik')], max_length=100, null=True),
        ),
    ]
